# Generated by Django 3.1.7 on 2021-04-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagescore',
            name='image_path',
            field=models.URLField(),
        ),
    ]
